### ISSUE TITLE
Using database from GitHub

### ISSUE THREAD

**Issue by Elsie19** [tlikonen/tagdb#1]
Title is a bit confusing but I have a program that has a search function and I want to use tags, but I don’t want to download the database to the local machine. What I want is for the database to be updated on the github repo, and users can search the remote database from their computer. Is that possible?

**Comment by tlikonen** [comment]
Tagdb is a command-line tool for personal notes. The database backend is Sqlite, so it's a file on user's personal profile on a computer.
